### ISSUE TITLE
Look deeper at open now functionality

### ISSUE THREAD

**Issue by z3cka** [z3cka/libraryweb-site#26]
The "Open Now" feature may be displaying innaccuratly for ~10-15min ... needs more research. The was discovered at the second QA session on Friday.

**Comment by z3cka** [comment]
a deeper look has shown that we have a caching issue. will be building a javascript approach that makes ajax request after page load to avoid page/block level caching.

**Comment by emb03** [comment]
wouldn't it be less effort to set the cron settings accordingly, like we did for the last iteration?
https://www-test.library.ucla.edu/admin/config/system/cron/settings
It looks like this got wiped out on www-test

**Comment by emb03** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10117750-301797991_1-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by z3cka** [comment]
clearing cache all the time _(every hour)_ kills performance

**Comment by emb03** [comment]
with elysian cron you can granularly clear only what you need, does that cause a load on the server that's noticeable?

**Comment by z3cka** [comment]
every location and destination page cache would need to be cleared every time each opens and closes

**Comment by z3cka** [comment]
plus it would be just as much effort to understand, implement, and test a cron cache clearing strategy that keeps the open now feature accurate

**Comment by emb03** [comment]
yes, but you have to deal with custom code otherwise

**USAGE EXAMPLES**

Elysia cron is usually used in large sites that needs performance optimization.

n, but don't want to execute ALL drupal cron tasks that often! For example, you may want to check for emails that needs to be sent to your users every 2 minutes. Standard cron is managed in a "monolithic" way, so even if you find out how to execute it every 2 minutes, you will end in having all cron tasks executed so often, with a lot of performance problems.

**Comment by z3cka** [comment]
it looks like there are some tools for this ... https://drupal.stackexchange.com/questions/25121/clear-a-single-url-from-cache 

but a simple ajax call on page load is much less complex and will work with our current MVP server setup... memcache and varnish in front of drupal's cache puts a wrinkle in things

**Comment by emb03** [comment]
It's simple if you understand what it is, where it is, and what it does. Future inheritors of the site may not find the copious documentation that i am sure you are writing :)

**Comment by z3cka** [comment]
hmmm, all of those modules are old and in alpha, beta, and rc status :-(

**Comment by emb03** [comment]
also looks like locations is cache-excluded but not destinations:
https://www-test.library.ucla.edu/admin/config/system/cacheexclude

**Comment by z3cka** [comment]
by drupal, but not varnish... this is exactly my point; our setup does not behave as expected

**Comment by z3cka** [comment]
Proof:
```
http -h http://www-test.library.ucla.edu/location/arts-library
HTTP/1.1 200 OK
Cache-Control: public, max-age=900
Connection: keep-alive
Content-Encoding: gzip
Content-Language: en
Content-Length: 8304
Content-Type: text/html; charset=utf-8
Date: Thu, 06 Jul 2017 22:01:55 GMT
Etag: "1499365215.584-1"
Last-Modified: Thu, 06 Jul 2017 18:20:15 GMT
Server: Apache
Vary: Cookie,Accept-Encoding
Via: 1.1 varnish
X-Cache: HIT
X-Cache-Hits: 1
X-Cacheable: YES
X-Content-Type-Options: nosniff
X-Drupal-Cache: HIT
X-Generator: Drupal 7 (http://drupal.org)
X-Powered-By: PHP/5.3.3
X-UA-Compatible: IE=edge,chrome=1
X-Varnish: 1207873935 1207873934
age: 0
```

**Comment by z3cka** [comment]
Damn, no difference... cache still in varnish... can't reset it :-(
```
http -h http://www-test.library.ucla.edu/location/arts-library
HTTP/1.1 200 OK
Cache-Control: public, max-age=900
Connection: keep-alive
Content-Encoding: gzip
Content-Language: en
Content-Length: 8304
Content-Type: text/html; charset=utf-8
Date: Thu, 06 Jul 2017 22:07:09 GMT
Etag: "1499365215.584-1"
Last-Modified: Thu, 06 Jul 2017 18:20:15 GMT
Server: Apache
Vary: Cookie,Accept-Encoding
Via: 1.1 varnish
X-Cache: HIT
X-Cache-Hits: 3
X-Cacheable: YES
X-Content-Type-Options: nosniff
X-Drupal-Cache: HIT
X-Generator: Drupal 7 (http://drupal.org)
X-Powered-By: PHP/5.3.3
X-UA-Compatible: IE=edge,chrome=1
X-Varnish: 1207873965 1207873934
age: 0
```

**Comment by z3cka** [comment]
using js is just easier and will increase page load speed as well as php does not need to do a call to the api every time.

**Comment by emb03** [comment]
https://www.drupal.org/project/purge
or a module

**Comment by z3cka** [comment]
cool. thanks for that. will look into it; but still a lot of discovery involved with this approach and I've got to deploy this feature next week.

**Comment by emb03** [comment]
also might be good for  handling forms as well:
https://www.thirdandgrove.com/using-drupal-ajax-forms-with-varnish-cache
I know you are under extreme pressure and I am just distracting you

**Comment by z3cka** [comment]
also, I got my selenium driver working with headless firefox to take screenshots:
![test](https://user-images.githubusercontent.com/230045/27935144-16e2768c-625e-11e7-81a9-dea00a176a68.png)
plus a new GitLab CI pipe working: https://gitlab.loaderboater.com:4433/z3cka/libraryweb-site/pipelines

**Comment by z3cka** [comment]
these are all good things to look at for understanding the best performance and load handling of our site, but I think they are out of scope with the Hour API project.

**Comment by z3cka** [comment]
all of today's tests are passing https://79585799.ngrok.io/ ... but I expect these to start failing at 5pm today... we shall see.

**Comment by emb03** [comment]
wait I thought gitlabs was replacing that ^^, doesn't gitlab do the same thing?

**Comment by z3cka** [comment]
it will eventually... but gitlabs reports are different and do not provide the same level of feedback; example report is singular: https://gitlab.loaderboater.com:4433/z3cka/libraryweb-site/-/jobs/68 ... but maybe I could generate an artifact or something to show the desired chart... here is gitlabs default chart: https://gitlab.loaderboater.com:4433/z3cka/libraryweb-site/pipelines/charts quite different... my other thing is custom so it shows exactly what I want to measure.

**Comment by z3cka** [comment]
bingo: https://79585799.ngrok.io/
<img width="616" alt="screen shot 2017-07-06 at 5 35 18 pm" src="https://user-images.githubusercontent.com/230045/27938245-86b5b4c0-6271-11e7-9961-eef078222e73.png">
_taken Jul 6 @ 17:35_

**Comment by z3cka** [comment]
and the corresponding test fail from gitlab: https://gitlab.loaderboater.com:4433/z3cka/libraryweb-site/-/jobs/71 :-(

**Comment by emb03** [comment]
These are the cron settings on www-stage (which is correct)

[cid:41942F43-5673-4C6F-9022-E930CAEF5722@host.ucla.edu]

and on www-test:

this is gone now.

Just sayin.....


On Jul 6, 2017, at 5:38 PM, Casey Grzecka <notifications@github.com<mailto:notifications@github.com>> wrote:


and the corresponding test fail from gitlab: https://gitlab.loaderboater.com:4433/z3cka/libraryweb-site/-/jobs/71 :-(

**Comment by emb03** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/8706172-301797991_1-s4-v1.png?transparent=1&palette=1&width=246)
